version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Building Spring Boot application
      - mvn clean package -DskipTests

      - echo Building Docker image
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $ECR_URI:$IMAGE_TAG