version: 0.2

env:
  variables:
    ECR_URI: 009736587590.dkr.ecr.ap-southeast-2.amazonaws.com/rpf-ecr-repo
    ECR_REPOSITORY: rpf-ecr-repo
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 009736587590.dkr.ecr.ap-southeast-2.amazonaws.com/rpf-ecr-repo

  build:
    commands:
      - echo Building Spring Boot application
      - mvn clean package -DskipTests

      - echo Building Docker image
      - docker build -t rpf-ecr-repo:latest .

      - docker tag rpf-ecr-repo:latest 009736587590.dkr.ecr.ap-southeast-2.amazonaws.com/rpf-ecr-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push 009736587590.dkr.ecr.ap-southeast-2.amazonaws.com/rpf-ecr-repo:latest